hyper_parameter:
  learning_rate: 0.0001  # 1e-4 -> 1.0e-4 for float representation
  clip_len: 16
  ratio_ssi: 1
  ratio_tgm: 10
  ratio_ssi_image : 0.5
  epochs: 200
  patient: 5
  batch_size: 2
  conv_out_channel: 64
  conv: true
  diff: true